### PR TITLE
HelpButton Attribute

### PR DESCRIPTION
**Pull request by ajboni**
Adds a toggleable help button that shows a help box.
gif

### CODE REVIEW

**Comment by vexe** [comment]
How about you merge this button functionality with the Comment attribute?

[Comment("This is a help text", Button = true)]

**Comment by ajboni** [comment]
Yes, good idea.

**Comment by ajboni** [comment]
Like this? https://github.com/rodobodolfo/VFW/commit/58bfe0473825d7cc3ac3e94f7f6843702517c03e
Had to make it pop at the bottom of the field, because otherwise it would move the field down and felt weird.

**Comment by vexe** [comment]
Yeah that's fine.

**Pull request closed without merging**
